In [1]:
import pandas as pd

In [3]:
# read fight night csv

df=pd.read_csv('fighter_scraper/fightnightpandas.csv')

df

,date,location,link
0,"December 19, 2020","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/e49c2db9...
1,"December 05, 2020","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/398b440e...
2,"July 30, 2022","Dallas, Texas, USA",http://www.ufcstats.com/event-details/b0a61247...
3,"December 12, 2020","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/d0d43cb9...
4,"February 13, 2021","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/3f7c14c7...
...,...,...,...
609,"June 18, 2022","Austin, Texas, USA",http://www.ufcstats.com/event-details/a0a680fe...
610,"July 16, 2022","Elmont, New York, USA",http://www.ufcstats.com/event-details/8fd76e1b...
611,"July 23, 2022","London, England, United Kingdom",http://www.ufcstats.com/event-details/319c15b8...
612,"July 02, 2022","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/4a9e3056...
613,"July 09, 2022","Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/31da66df...

New

In [5]:
pd.read_html(df['link'][0])[0]

,W/L,Fighter,Kd,Str,Td,Sub,Weight class,Method,Round,Time
0,win,Stephen Thompson Geoff Neal,0 0,171 85,0 0,0 0,Welterweight,U-DEC,5,5:00
1,win,Jose Aldo Marlon Vera,0 0,44 46,0 0,0 0,Bantamweight,U-DEC,3,5:00
2,win,Michel Pereira Khaos Williams,0 0,44 55,2 0,1 0,Welterweight,U-DEC,3,5:00
3,win,Rob Font Marlon Moraes,1 0,30 9,0 2,0 0,Bantamweight,KO/TKO Punches,1,3:47
4,win,Marcin Tybura Greg Hardy,0 0,51 50,1 0,0 0,Heavyweight,KO/TKO Punches,2,4:31
5,win,Anthony Pettis Alex Morono,0 0,50 31,0 1,0 0,Welterweight,U-DEC,3,5:00
6,win,Pannie Kianzad Sijara Eubanks,0 0,92 49,0 2,0 0,Women's Bantamweight,U-DEC,3,5:00
7,win,Deron Winn Antonio Arroyo,0 0,20 45,12 0,0 0,Catch Weight,U-DEC,3,5:00
8,win,Taila Santos Gillian Robertson,0 0,27 9,1 0,1 1,Women's Flyweight,U-DEC,3,5:00
9,win,Tafon Nchukwi Jamie Pickett,1 0,120 40,0 1,0 0,Middleweight,U-DEC,3,5:00
10,win,Jimmy Flick Cody Durden,0 0,6 21,0 2,1 0,Flyweight,SUB Triangle Choke,1,3:18
11,win,Christos Giagos Carlton Minus,0 0,31 28,5 0,0 0,Catch Weight,U-DEC,3,5:00

In [42]:


data = pd.DataFrame()

for index, row in df.iterrows():
    # this gets the table information from the url
    tempdf = pd.read_html(row['link'])[0]
    # clean the table
    tempdf=tempdf[['W/L','Fighter','Method','Round','Time']]
    # combine the table with scraped information
    tempdf['location']=row['location']
    tempdf['date']=row['date']
    # concat
    data = pd.concat([data,tempdf])

In [55]:
# count unique fights

data.nunique()

W/L            3
Fighter     6630
Method        71
Round          5
Time         339
location     167
date         609
dtype: int64

In [56]:
data.isnull().sum()

W/L         13
Fighter      0
Method      13
Round       13
Time        13
location     0
date         0
dtype: int64

In [57]:
data=data.dropna(axis=0, how='any')

In [54]:
data[['Method']]

               Method
0               U-DEC
1               U-DEC
2               U-DEC
3     KO/TKO  Punches
4     KO/TKO  Punches
..                ...
6       KO/TKO  Punch
7               S-DEC
8   SUB  Arm Triangle
9      KO/TKO  Elbows
10              U-DEC

[6744 rows x 1 columns]

In [61]:
# get rid of time column - Round is bascially a binned version of time which is more readable by algorithms

data=data[['W/L', 'Fighter', 'Method', 'Round', 'location', 'date']]

In [64]:
# save to csv

data.to_csv('fights-all.csv', index=False)

In [8]:
df = pd.read_csv('fighter_scraper/fights-all.csv')